project:
  type: website

website:
  title: "10mapz: geo data visualization"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - courses.qmd
      - workshops.qmd
      - consulting.qmd
      - portfolio.qmd
      - blog.qmd
      - about.qmd

format:
  html:
    theme: default
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto
