project:
  type: website

website:
  title: "<strong>10mapz</strong> <span class='site-subtitle'>geospatial visualization</span>"
  favicon: 10mapz2.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - courses.qmd
      - consulting.qmd
      - about.qmd

format:
  html:
    theme: default
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto
