project:
  type: website
  
website:
  favicon: 10mapz3.ico
  title: "<strong>10mapz</strong> <span class='site-subtitle'>geospatial visualization</span>"
  navbar:
    logo: 10mapz3.png
    left:
      - href: index.qmd
        text: Home
      - courses.qmd
      - consulting.qmd
      - about.qmd

format:
  html:
    theme: default
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto
